version: "3"
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database_name
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:5000
    depends_on:
      - db
    volumes:
      - ./templates:/app/templates
    environment:
      DATABASE_URL: postgresql://your_username:your_password@db/your_database_name

volumes:
  db_data:
